# Generated by Django 3.0.6 on 2020-05-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastsandroasts',
            old_name='downvote',
            new_name='downvotes',
        ),
        migrations.RenameField(
            model_name='boastsandroasts',
            old_name='upvote',
            new_name='upvotes',
        ),
    ]
