# Generated by Django 3.0.6 on 2020-05-14 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0002_auto_20200514_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsandroasts',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
