# Generated by Django 3.0.6 on 2020-05-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0003_boastsandroasts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boastsandroasts',
            old_name='downvotes',
            new_name='votescore',
        ),
        migrations.RemoveField(
            model_name='boastsandroasts',
            name='upvotes',
        ),
    ]
