# Generated by Django 3.0.6 on 2020-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0004_auto_20200514_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsandroasts',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boastsandroasts',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
