# Generated by Django 3.0.6 on 2020-05-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0005_auto_20200515_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastsandroasts',
            name='is_boast',
            field=models.BooleanField(default=True),
        ),
    ]
