# Generated by Django 3.0.6 on 2020-05-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gposts', '0006_boastsandroasts_is_boast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastsandroasts',
            name='is_boast',
            field=models.BooleanField(),
        ),
    ]
